### PR TITLE
httpauth: Refactor out Mutex

### LINKED ISSUE #10: AuthenticationMiddleware was called already panic
We are observing that our actix-web application occasionally panics under a lot of contention with the message "AuthenticationMiddleware was called already". This seems to come from here https://github.com/actix/actix-web-httpauth/blob/v0.4.0/src/middleware.rs#L184

We have recently migrated to actix-web 2.0 and actix-web-httpauth 0.4. We haven't observed this before the migration.

As this doesn't happen for all requests, there seems to be some race condition either within actix-web or actix-web-httpauth that causes this.

We use bearer token authorization and within the validation function, to validate the token, we just perform an HTTP request with reqwest and depending on the result return Ok or Err.

### PR DESCRIPTION
**Pull request by boydjohnson**
Fixes #10

### CODE REVIEW

**Comment by cetra3** [comment]
I'm a little worried that there hasn't been a repro for #10 and would be reluctant at introducing yet another mutex implementation without solid test cases.  As you said, this is based on *trial and error*, and I think having a test case to prove that this is correct would be needed.

There appears to be some upstream issue that is causing `try_lock()` to return `None`, so we need to understand why that is happening first, as it is very much exceptional circumstances.  The `&mut self` on both methods should not really allow for this to happen, so that needs to be sorted out why it's happening in the first place & may not even be related here.

**Comment by boydjohnson** [comment]
Thanks for the quick reply @cetra3 . I will work on some unit test cases for this situation. I'm going to first look at other tests for Service throughout the different actix codebases, to see if there is something useful there.

**Comment by boydjohnson** [comment]
Hi @cetra3 On master, this test fails with a panic ```test middleware::tests::test_middleware_mutex ... FAILED

failures:

---- middleware::tests::test_middleware_mutex stdout ----
thread 'middleware::tests::test_middleware_mutex' panicked at 'AuthenticationMiddleware was called already', actix-web-httpauth/src/middleware.rs:183:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Panic in Arbiter thread.
```

On this branch it passes.

**Comment by cetra3** [comment]
Thanks for your test, I can replicate the issue with the current master

However: If you use the same strategy you have, (polling the lock rather than panicking), the tests past without having to add a new dependency on `future-parking_lot`

I.e:

```rust
    fn poll_ready(&mut self, ctx: &mut Context<'_>) -> Poll<Result<(), Self::Error>> {
        match self
            .service
            .lock()
            .boxed_local()
            .as_mut()
            .poll(ctx)
            .map(|mut s| s.poll_ready(ctx))
        {
            Poll::Ready(inner) => inner,
            Poll::Pending => Poll::Pending,
        }
    }
```

Can you confirm if that works for your trial & error scenario as well.

**Comment by boydjohnson** [comment]
Hi @cetra3 I see that using the futures_utils::Mutex passes the test. It doesn't pass my trial and error approach which is to run a workload generator on an actix api with the Auth Middleware. I run the generator for 10 seconds and then run it again for 10 seconds. On the second try it no longer responds and does 0requests/sec which I am attributing to a deadlock. Do you suggest that I find a unit test that will show this failure?

**Comment by cetra3** [comment]
There is also another method, which skips a box pin allocation on the `poll_ready` method that appears to work on tests (but can result in false positives on poll_ready which [is allowed](https://docs.rs/actix-web/3.0.0-alpha.3/actix_web/dev/trait.Service.html#tymethod.poll_ready) according to API)

```rust
    fn poll_ready(&mut self, ctx: &mut Context<'_>) -> Poll<Result<(), Self::Error>> {
        match self.service.try_lock() {
            Some(mut guard) => guard.poll_ready(ctx),
            None => Poll::Ready(Ok(())),
        }
    }
```

**Comment by boydjohnson** [comment]
Hi @cetra3 That passes my trial and error test. I am hesitant since it doesn't make sense to me. Returning Poll::Ready(Ok(())) when the lock isn't available would tell the runtime to call `call` when the lock isn't ready. I tried with Poll::Pending but that doesn't pass the trial and error test. Can we talk that code through? Why did you choose Poll::Ready instead of Poll::Pending?

**Comment by cetra3** [comment]
If you return `Poll:Pending` from that second example it will not ever wake up as `try_lock` does not have the side effect of registering a waker as per `lock()`, so the task will never be notified.  It is OK, but a bit ugly as you said, according to the API to return `Poll:Ready` (i.e, false positive).

I agree, I don't think it's finished code, or an acceptable permanent solution, but it is better than panicking or introducing a new dependency.

On a closer look at existing implementations, I think refactoring it to remove the `Mutex` altogether may be a viable solution.  Having a look at some of the other middlewares in this package, none of them use a `Mutex`.  There was a similar issue to this with the identity middleware: [1263](https://github.com/actix/actix-web/issues/1263) which may be a good starting point.

**Comment by boydjohnson** [comment]
I'll take a look at the identity middleware. Thanks for your advice. It may be a few days until I get back to this.

**Comment by boydjohnson** [comment]
Hi @cetra3 I ran a workload generator for 8 minutes twice on an actix-web api with this PR branch and there was no panic.

**Comment by cetra3** [comment]
That looks good.  The next steps are we need to get the original issue raiser to see if your PR works for them & then get sign off from other members

**Comment by stiiifff** [comment]
Tested on my end and it looks good !

**Comment by robjtede** [comment]
The patch looks good. I think it would be worth documenting this nuance about locking/borrowing across await points for future middleware makers. For now, can we add in just a line above the await pointing out the pitfall avoided.

**Comment by boydjohnson** [comment]
@robjtede I added in a comment.

**Pull request merged**
