### PR TITLE
Make it work with actix-web 4.0.0-beta.7

### PR DESCRIPTION
**Pull request by andy128k**
## PR Type
Bug Fix

## PR Checklist
Check your PR fulfills the following:

- [x] Tests for the changes have been added / updated.
- [x] Format code with the latest stable rustfmt

## Overview

Make it work with latest beta of actix-web. ~~Requires https://github.com/actix/actix-web/pull/2168~~

### CODE REVIEW

**Comment by tyranron** [comment]
@andy128k any chance to finish it nad merge it soon? We can't upgrade to `4.0.0-beta.6` `actix-web` few months already.

**Comment by andy128k** [comment]
@tyranron Actually there are no changes in this branch since mid of April. I only update it from time to time to make it work with `actix-web`'s master.

**Comment by andy128k** [comment]
@tyranron  `actix-web` of version `4.0.0-beta.6` doesn't work with `actix-extra` (it just doesn't have required API).
So, you either stick to `beta.5`, or use `master` branch. 

@robjtede  I'd suggest to release `4.0.0-beta.7` of `actix-web`, then this PR may be merged (and probably also released as a next beta).

**Comment by thalesfragoso** [comment]
The new version of `cargo-cache` uses `resolver = "2"` which is blocking the MSRV CI, we could try changing:
https://github.com/actix/actix-extras/blob/64eec6e5502f1923c202c88459dfae03cec0ae21/.github/workflows/ci.yml#L104

to 
```
cargo install cargo-cache --version 0.6.2 --no-default-features --features ci-autoclean
```

**Comment by thalesfragoso** [comment]
Sorry, I missed another use of it at the end of the file :/

**Comment by andy128k** [comment]
@thalesfragoso Thanks a lot.

**Comment by andy128k** [comment]
Now the only blocker of this PR is a dependency on unpublished version of `actix-test`.

**Comment by robjtede** [comment]
yeah the redis tests only work on linux so you need to add the exclude back

**Comment by robjtede** [comment]
I don't know what you're trying to do with the CI but it'd be better to do in it's own PR. Dont worry about fixing the macOS jobs. I will test locally before merging.

**Comment by andy128k** [comment]
That's strange. Test are passing locally on both Linux and macOS.

**Comment by andy128k** [comment]
Pushed to trigger CI to test with actix-web 4.0.0-beta.8. No changes in the code.

**Pull request closed without merging**
