### PR TITLE
fix: broken stream when authentication failed

### PR DESCRIPTION
**Pull request by RolandMa1986**
## PR Type

 Bug Fix 

## PR Checklist

- [x] Tests for the changes have been added / updated.
- [x] Documentation comments have been added / updated.
- [x] A changelog entry has been made for the appropriate packages.
- [x] Format code with the nightly rustfmt (`cargo +nightly fmt`).

## Overview

The handler's signature has been changed. I'm not sure whether it's acceptable. Please let me known it there's a better solution.

### CODE REVIEW

**Review by JohnTitor — APPROVED** [review]
Looks sensible, +1

**Comment by RolandMa1986** [comment]
I don't see any relations between the commit and the failing doc tests.  How do i  to fix it?

**Comment by JohnTitor** [comment]
Due to https://github.com/rust-lang/rust/issues/99261, let's ignore it for now.

**Review by robjtede — APPROVED** [review]
change seems fine, no better way to do it with the current middleware system so worth providing _a_ solution instead of none

**Comment by jacob-pro** [comment]
this is a neat way of solving the bug within the current constraints - thank you @RolandMa1986

**Pull request merged**
