### PR TITLE
Add note for accessing session state in stream.

### PR DESCRIPTION
**Pull request by mohe2015**
## PR Type

Small documentation improvement.

## PR Checklist

- [x] Tests for the changes have been added / updated.
- [x] Documentation comments have been added / updated.
- [x] A changelog entry has been made for the appropriate packages.
- [x] Format code with the nightly rustfmt (`cargo +nightly fmt`).

## Overview

I found out that you can't even read the session state in a stream of a streaming response. This may be unintentional behaviour as I think reading could be possible just not writing as the headers have already been sent. In any case I think it may be helpful to document this.

### CODE REVIEW

**Comment by robjtede** [comment]
I don't really understand what you're expecting to work here. Can you give a psuedo-code example of what you want to write?

**Comment by mohe2015** [comment]
> I don't really understand what you're expecting to work here. Can you give a psuedo-code example of what you want to write?

To be honest my explanation was a bit short. I wrote a reproducer in https://github.com/mohe2015/actix-extras-285/blob/main/src/main.rs

If I didn't mess anything up in a perfect world I would expect the set-broken and get-broken to either not compile or to panic. To my understanding they silently don't contain the data of the session. It is clear though that setting the data is not supposed to work as the headers have already been sent (potentially).

**Review by robjtede — APPROVED** [review]

**Comment by robjtede** [comment]
Thanks for showing how you're wanting to use it, the added note makes more sense now.

**Comment by mohe2015** [comment]
A question I have is whether I should open an issue to improve this behaviour (especially on the reading side)?

**Pull request merged**
