### PR TITLE
Rebuild `actix-identity` on top of `actix-session`

### PR DESCRIPTION
**Pull request by LukeMathWalker**
This is a rewrite of `actix-identity`.

# Why?

`actix-identity` and `actix-session` have historically created confusion in developers that are approaching `actix-web`'s ecosystem for the first time: which one should I use if I want to add session-based authentication to my application?  
`actix-session` offered a more general-purpose API (lower-level, if you want), while `actix-identity` had some pretty convenient extractors. Starting with `actix-identity` was usually easier (a more opinionated API, geared for auth), but if you outgrew it (e.g. you now want to store more than identity into the session) you'd have to rewrite everything from scratch to use `actix-session`, including the auth part.

From a maintenance perspective, `actix-identity` and `actix-session` shared no code.  
Any change/fix/improvement to the logic related to the management of the session cookie, additional storage backend, etc. required duplication of effort. In reality, they often diverged or features were available in one of the two but not the other (e.g. `actix-identity` never supported remote storage backends).

By rebuilding `actix-identity` on top of `actix-session` we can solve both problems at once: we get, out of the box, lower maintenance overhead, feature parity and a clear onboarding path for developers who want to work with sessions (for auth or otherwise).

# How?

I ported over all existing features of `actix-identity`: extractor, login deadline, visit deadline.  
This PR is built on top of the branch for #233, therefore #233 must be merged first into trunk.  
This PR introduces a few more breaking changes to `actix-session`, on top of the ones already in #233:

- We return a custom error type for `Session::get` and `Session::insert`. This will make it easier to evolve the API in the future and gives us a way to provide a more helpful error message (i.e. it includes details on the key you were trying to access/insert).

### CODE REVIEW

**Comment by LukeMathWalker** [comment]
This has a few breaking changes in `actix-session` as well @robjtede - it should go in before cutting a new release.

**Comment by LukeMathWalker** [comment]
Resolved all conflicts ✅

**Review by robjtede — APPROVED** [review]

**Comment by robjtede** [comment]
@LukeMathWalker good to release -session and -identity ?

**Comment by LukeMathWalker** [comment]
Good to go for me!

**Comment by robjtede** [comment]
@LukeMathWalker released -session v0.7.0 (🎉) but realized that -identity doesn't didn't get anything added to the changelog. Do you mind writing something up and I'll get -identity out, too.

**Pull request merged**
