### PR TITLE
fix: bad interaction between session state changes and renewal

### LINKED ISSUE #244: Bad interaction between session state changes and renewal
We suffer from the same bug reported against `poem`'s `Session` implementation - see https://github.com/poem-web/poem/issues/196

### PR DESCRIPTION
**Pull request by Hulxv**
## PR Type

Bug Fix

## PR Checklist

- [x] Tests for the changes have been added / updated.
- [x] Documentation comments have been added / updated.
- [x] A changelog entry has been made for the appropriate packages.
- [x] Format code with the nightly rustfmt (`cargo +nightly fmt`).

## Overview

Closes  #244

### CODE REVIEW

**Comment by robjtede** [comment]
For the sake of readers like me who haven't really looked into the problem, is there a comment that can be left on these conditionals explaining the behavior? Not obvious at first glance (to me) what this solves.

**Comment by Hulxv** [comment]
That's a simple explanation for the issue from [poem-web/poem#196](https://github.com/poem-web/poem/issues/196) and that issue happens in `actix-session` too.

> ## Expected Behavior
> 
> When using Session, calling `session.renew()` always renews the session, indepentent of it's location in the handler (unless there is a `session.purge()`).
> 
> ## Actual Behavior
> When calling `session.set("x", "y")` after `session.renew()`, the session does not get renewed.
> 
> From my understanding of the code, this is caused by this line in `session.set()` (and `session.remove()`):
> https://github.com/poem-web/poem/blob/ad20fe7ebaf9660a295d1af194ee82b6d2d80037/poem/src/session/session.rs#L85
> 
> This unconditionally overwrites the status and deletes the information that a session renew was requested. What I think should happen instead is that it only overwrites the status if it is currently set to `Unchanged`.

**Comment by robjtede** [comment]
Ok, got it. So, if I understand correctly, this won't break the other way because a renewed session will reassign the cookie with the changed state as well.

**Comment by Hulxv** [comment]
> is should make the state more like setting independent boolean flags than an enum? 

Nope, Enums is working well and I think I resolved the issue that is happening.

@LukeMathWalker Can you give us your opinion?

**Comment by LukeMathWalker** [comment]
I think @robjtede's intuition is correct - renewing the session id and changes the session state are independent and should be tracked separately.

**Comment by Hulxv** [comment]
So is there anything I should do more or is everything just fine?

**Comment by robjtede** [comment]
My concern is that this might break it the other way; storage implementations handle independently a change in session content and session lifespan.

It would not affect cookie storage but in Redis storage is would be the different... eg:
```
CHANGED           => SET key new_contents
RENEWED           => TTL key ttl
CHANGED + RENEWED => SETX key new_contents ttl
```
^ untested but hopefully you see the point

**Comment by robjtede** [comment]
Here's what I want to know:
1. Does this fix the issue #244 without introducing new bugs?
2. Is this the ideal set up of session state and TTL metadata?

**Comment by Hulxv** [comment]
> 1. Does this fix the issue #244 without introducing new bugs?

I think yes because that is the way how `poem`  developers solved this issue and there's no one reported another issue about that more and they never change [session.rs](https://github.com/poem-web/poem/blob/master/poem/src/session/session.rs) after [20532aa](https://github.com/poem-web/poem/commit/20532aa06bcbb4bc122d67d3a4fc0b5fcf68eef4).

> 2. Is this the ideal representation of session state and TTL metadata?


Honestly, I'm don't familiar with `Redis`, So, I don't understand what you mean here
```
CHANGED           => SET key new_contents KEEPTTL
RENEWED           => SETEX key ttl
CHANGED + RENEWED => SET key new_contents EX ttl
```
and I don't know what the ideal representation.

**Comment by LukeMathWalker** [comment]
This should not introduce new bugs, as far as my understanding goes. 

The middleware instructs the backend to perform a delete on the data associated with the old session key and a save of the current session state against the new key (see https://github.com/actix/actix-extras/blob/cfd16c54781a154f937bbbddf605bb0ce7a2e564/actix-session/src/middleware.rs#L275), so this should behave correctly regardless of the session storage implementation details.

**Review by robjtede — APPROVED** [review]

**Pull request merged**
