### PR TITLE
Update dependencies (Tokio 1.0)

### PR DESCRIPTION
**Pull request by andy128k**
## PR Type

Refactor

## PR Checklist
Check your PR fulfills the following:

- [x] Format code with the latest stable rustfmt

## Overview

Update dependencies to use crates with Tokio 1.0.

### CODE REVIEW

**Comment by robjtede** [comment]
Thanks for this. I'm going to keep this PR open until v4 is stable to reduce churn since there are more breaking changes to come.

**Comment by robjtede** [comment]
new MSRV is 1.46 btw

**Comment by andy128k** [comment]
PR is updated to latest versions.

Additionally, `actix-redis` is rewritten to not to use deprecated `actix::actors::resolver`.

**Comment by izik1** [comment]
@andy128k actix-web out of date?

**Comment by andy128k** [comment]
@izik1 It is not. Cargo fetches 4.0.0-beta.3 even if `4.0.0-beta.1` is specified. They are semver-compatible.

**Comment by andy128k** [comment]
`redis_async` was updated to 0.9

**Comment by robjtede** [comment]
Alright, I'm declaring this repo ready for tokio v1 merges. We can do one or two sets of betas for the extras crates.

**Comment by fakeshadow** [comment]
trust-dns is removed for the reason of reduce code bloat and improve compile time. tbh I don't see the need to rewrite it in actix-redis. It's not like it need cache and performance. I would suggest you use `actix_tls::connect::default_connector` service. It would be much simplier and would still open up custom dns resolver if needed.

**Comment by andy128k** [comment]
@fakeshadow I am not sure if I understand your suggestion. `redis_async` does not allow to pass an opened socket to it, but just an address.

**Comment by fakeshadow** [comment]
`actix_tls::connect` is the connector service actix-web use. It has a default dns resolvre and also can extend with a custom resolver if you want to.
You can see this piece of doc on how to use it https://docs.rs/actix-tls/3.0.0-beta.4/actix_tls/connect/fn.default_connector.html.

Basically you can box the return type of this function and use it as redis actor state. Then you would be able to call this service, pass a Connect<String> type to it and get a Connection<String, TcpStream> back where the String is host address and TcpStream is already established one after dns resolve.

**Comment by robjtede** [comment]
We can do the resolver rewrite in separate pr. Resolver is not removed in 0.11 only deprecated.

**Review by robjtede — APPROVED** [review]
LGTM, nice work

**Pull request merged**
