### PR TITLE
feat(cors): allow using closures in allow_origin_fn

### PR DESCRIPTION
**Pull request by pldin601**
## PR Type

Feature

## PR Checklist
Check your PR fulfills the following:

- [x] Tests for the changes have been added / updated.
- [x] Documentation comments have been added / updated.
- [x] A changelog entry has been made for the appropriate packages.
- [x] Format code with the latest stable rustfmt

## Overview

Allow using closures as arguments passed to allowed_origin_fn.

### CODE REVIEW

**Comment by robjtede** [comment]
Can you add a test for something that wasn't possible before and add a changelog entry.

**Comment by pldin601** [comment]
@robjtede done.

**Review by robjtede — COMMENTED** [review]
nice change, thanks 👍

**Review by robjtede — APPROVED** [review]

**Comment by robjtede** [comment]
released in 0.4.1

**Pull request merged**
