### PR TITLE
document settings crate

### PR DESCRIPTION
**Pull request by robjtede**
## PR Type

Docs

## PR Checklist

- [x] Tests for the changes have been added / updated.
- [x] Documentation comments have been added / updated.
- [x] ~~A changelog entry has been made for the appropriate packages.~~
- [x] Format code with the nightly rustfmt (`cargo +nightly fmt`).

## Overview
Docuemnt crate in preparation for publishing new version.

cc @jjpe lmk if anything is inaccurate.

### CODE REVIEW

**Comment by robjtede** [comment]
@jjpe can you shed some light on the naming of `AtError` ?

**Comment by robjtede** [comment]
Ahh it'll be an `actix-toml` abbreviation (as seen in your repo's readme). I assume it was a working title?

**Comment by jjpe** [comment]
> I assume that was the working title.

Pretty much yeah. So the error should probably be renamed to either `Error` (letting the module name do the scoping) or to something like `SettingsResult` or `AsResult`. Personally I'd favor the first, as it's a common idiom, and the last one could easily get confused for a trait. The main issue with `SettingsResult` is the wordiness I think.

**Comment by robjtede** [comment]
My preference is also to just use `Error`. And likely make the `Result` convenience private. But again, I'll defer other API changes to a subsequent release.

**Pull request merged**
