### PR TITLE
Let the validation function decide whether to continue or abort request

### PR DESCRIPTION
**Pull request by stiiifff**
… processing based on the request, and the presence or absence of credentials.

This is a breaking change compared to the current implementation
The validation function is now defined as `Fn(ServiceRequest, Option<T>) -> O` instead of `Fn(ServiceRequest, T) -> O`.
This allows to cater for cases where e.g. some routes don't require authentication, or some other application-specific authorization logic.

Another approach could be to add a middleware setting to decide whether to abort the request if there is no credentials present in the request.

### CODE REVIEW

**Comment by Jonathas-Conceicao** [comment]
I'm not sure I get the point of this breaking change. If I get it right. The goal of this change is to allow authentication to be set to some routes but not others, if so. Why not just wrap the authentication middle on a specific `Resource` instead of the hole App? This is how I personally handle some routes having authentication while others doesn't.

**Comment by alexander-irbis** [comment]
@Jonathas-Conceicao while that solves the issue, it is not so convenient to make complicated setups just to exclude some routes from the authorization. Another issue is CORS: HttpAuth blocks the OPTIONS request from the browser with "401 Unauthorized" and the browser does not send the auth header. Although maybe there is a better way to resolve this conflict..

**Comment by GopherJ** [comment]
Totally agree @alexander-irbis

**Comment by stiiifff** [comment]
> I'm not sure I get the point of this breaking change. If I get it right. The goal of this change is to allow authentication to be set to some routes but not others, if so. Why not just wrap the authentication middle on a specific `Resource` instead of the hole App? This is how I personally handle some routes having authentication while others doesn't.

My use-case is a GraphQL API (using the juniper crate) where queries do not require auth but mutations do ... and both (queries & mutations) go through a single /graphql endpoint.

**Comment by GopherJ** [comment]
Is there anyone who can review this PR and accept it?

**Comment by Dowwie** [comment]
While I agree with the goal of having more flexible middleware, I disagree with how that is being achieved here.  This seems like a flawed design.  I use the other tools in the toolbox to achieve a finer level of authentication and haven't imposed changes upon the actix architecture to do so.

I respectfully disapprove of this change..

**Comment by stiiifff** [comment]
@Dowwie I’m happy to use a better solution if this is too much of a breaking change. What would be your approach for the use case I mentioned above ?

**Comment by Dowwie** [comment]
@stiiifff I've stayed away from GraphQL for a few reasons, security considerations being one (I've considered security too much already).  It may be that the App/Scope/Resource middleware you are working with isn't meant for GraphQL and are the wrong tools for the job-- you may be running into the ["streetlight effect"](https://en.wikipedia.org/wiki/Streetlight_effect).  

If GraphQL is really such a great level up for request/response flow, maybe it deserves its own new approach to authentication and authorization rather than trying to use that which is suited for RESTlike flow.  Sorry that I can't be more specific but I would have to learn more before sharing more concrete ideas.  In your case, you could write a middleware, using actix-net architecture (as-is), that will distinguish mutations from queries and enforce accordingly.

**Comment by cetra3** [comment]
I don't feel that it is worth introducing greater complexity to the standard basic auth/bearer middleware.  It seems like it's a bit of a niche case and the more common case is that you are always expecting the header or return unauthorised.  Otherwise it is less ergonomic to consume the middleware if it's optional.

Is basic auth the recommended approach for GraphQL?  All the guides look like they use tokens.

**Comment by stiiifff** [comment]
@cetra3 I'm using bearer auth, not basic auth.
Agreed that my use case should be catered for at another level than in the auth middleware.

**Comment by GopherJ** [comment]
@Dowwie Is there a good reason for closing this?

**Comment by GopherJ** [comment]
@cetra3 

> I don't feel that it is worth introducing greater complexity to the standard basic auth/bearer middleware. It seems like it's a bit of a niche case and the more common case is that you are always expecting the header or return unauthorised. Otherwise it is less ergonomic to consume the middleware if it's optional.

So you are saying giving users the right to decide on their own is **introducing complexity**?

**Comment by Dowwie** [comment]
The reason this issue is closed is that there is a viable path forward by using the tools already available.  This is only one instance of many where developers, including me, do not fully understand what to use when.  The immediate reaction is to just change and build towards a solution that works, rather then use what is already available.

**Comment by Dowwie** [comment]
> @cetra3 
> 
> > I don't feel that it is worth introducing greater complexity to the standard basic auth/bearer middleware. It seems like it's a bit of a niche case and the more common case is that you are always expecting the header or return unauthorised. Otherwise it is less ergonomic to consume the middleware if it's optional.
> 
> So you are saying giving users the right to decide on their own is **introducing complexity**?

Try to look at this as one episode of a long story where people try to change rather than learn and use that which is already available.  You can help influence change by showing how the existing tooling doesn't suffice.

**Comment by GopherJ** [comment]
@Dowwie So what if we would like to disable this level of secutiry in some cases? And what's the solution for controling many routes but some of those routes don't even need security? Will we need to wrap middleware one by one for those who needs?

**Comment by Dowwie** [comment]
> @Dowwie So what if we would like to disable this level of secutiry in some cases? And what's the solution for controling many routes but some of those routes don't even need security? Will we need to wrap middleware one by one for those who needs?

I recognize the rattling off of questions as impatience and aggravation.  Understand that we have shared incentives to improve this system.  It doesn't make sense to block useful changes.  I don't think anyone would do so. 

Actix-web and actix-web are really powerful as-is.  They already offer multiple ways to solve many problems.  One approach that I've found useful is to enforce fine grained security at the handler level, using custom extractors and or imperative style authorization using values from a request.

If you don't want handler level security and want controls at a more aggregate level, take the time to study your options using middleware.

Show how these are insufficient and we can improve.

**Comment by GopherJ** [comment]
@Dowwie The main issue is:
```
You are closing changes while having no proposed solution
```
I'm patient enough but still, I'm just an actix user, I'd expect a *solution* for my cases, so in the case that you close a PR while not proposing any solution, it can be frustrating I would say, but anyway this will not cause major problems, I would keep using this PR and rebease for new changes.

**Comment by mike-lloyd03** [comment]
Is it possible to introduce a third middleware option that implements this rather than adding a breaking change to `HttpAuthentication::bearer`? Perhaps something like `HttpAuthentication::bearer_optional` that expects a validator function of `Fn(ServiceRequest, Option<BearerAuth>) -> O`? This would not add any new complexity to the currently implemented methods and would allow the users more flexibility when adding bearer auth to their service.

**Pull request closed without merging**
