### PR TITLE
allow user to set the cookie HttpOnly policy for the redis session

### PR DESCRIPTION
**Pull request by BartWillems**
Signed-off-by: Bart Willems

### CODE REVIEW

**Comment by BartWillems** [comment]
Are these code coverage tests blocking?

**Comment by robjtede** [comment]
not really blocking but might be nice to include setting and checking in one of the examples

**Comment by JohnTitor** [comment]
Looks good, could you also update changelog?

**Comment by BartWillems** [comment]
@JohnTitor I've updated the changelog

**Pull request merged**
