### PR TITLE
update actix dependencies to the latest betas

### PR DESCRIPTION
**Pull request by DominicWrege**
## PR Type

Update

## PR Checklist
Check your PR fulfills the following:

- [x] Tests for the changes have been added / updated.
- [ ] Documentation comments have been added / updated.
- [x] A changelog entry has been made for the appropriate packages.
- [x] Format code with the latest stable rustfmt

## Overview

The goal was to updated all dependencies to work with the latest actix-web beta and fix all the tests.
There is one previews test failure in `session::test::test_session_workflow` which I did not fix.

### CODE REVIEW

**Comment by robjtede** [comment]
this and #144 are gonna have to fight it out :P

**Comment by therealprof** [comment]
Hm, not being able to use `actix-cors` blocks me from testing the actix/actix-web beta.

**Comment by robjtede** [comment]
you can use it with cargo git deps from this branch (using `git = "{git_url}", rev = "{commit_hash}"`

**Comment by therealprof** [comment]
@robjtede Good point, didn't think of that.

**Comment by therealprof** [comment]
OTOH it doesn't work without major magic since `actix-cors` is a workspace member and pseudo-virtual package of `actix-extras` and there's no `git` syntax for that.

**Comment by DominicWrege** [comment]
@therealprof can please you be more specific about your issue? I created a little `[example](https://github.com/DominicWrege/actix-beta-cors-example)` project which uses the actix-cors git version.

**Comment by therealprof** [comment]
> @therealprof can please you be more specific about your issue? I created a little [example](https://github.com/DominicWrege/actix-beta-cors-example) project which uses the actix-cors git version.

Hm, I tried:
```
actix-cors = { git="https://github.com/actix/actix-extras", rev="9f9690348be8224139c3672bbf4d8feb34393545"}
```

and it didn't work, your example does, using your repo it does work. Thanks!

**Comment by DominicWrege** [comment]
Yep wrong branch :)

**Comment by therealprof** [comment]
Any chance to get the versions bumped again? ;)

**Comment by DominicWrege** [comment]
> Any chance to get the versions bumped again? ;)

I am sorry, can you please explain what do you mean ?

**Comment by therealprof** [comment]
> I am sorry, can you please explain what do you mean ?

There're new releases of various actix crates, so the `Cargo.toml` needs an update.

**Comment by fakeshadow** [comment]
Newest release of beta crates have compat issue with actix-web v4 beta.1.
For now this PR better remain untouched on dep side until next actix-web beta release.
The CI fails for the same reason.

**Comment by DominicWrege** [comment]
Agree.

**Comment by robjtede** [comment]
#144 was merged. Thanks for your input regardless.

**Pull request closed without merging**
