### PR TITLE
add support for private network access cors header

### PR DESCRIPTION
**Pull request by robjtede**
## PR Type

Feature

## PR Checklist

- [x] Tests for the changes have been added / updated.
- [x] Documentation comments have been added / updated.
- [x] A changelog entry has been made for the appropriate packages.
- [x] Format code with the nightly rustfmt (`cargo +nightly fmt`).

## Overview

Implements the [Private Network Access](https://wicg.github.io/private-network-access) CORS extensions behind a flag so we can follow any spec changes while it's in draft.

### CODE REVIEW

**Comment by robjtede** [comment]
cc @GillesPl

**Comment by michallis** [comment]
> cc @GillesPl I presume this is something you need for work or whatever so if we get this merged it'd be nice to have some feedback :)

Dear... same here, working with GillesPI -> will give you feedback

**Comment by latin-1** [comment]
The specification has been renamed to local-network-access, and the headers have been renamed as well.

https://wicg.github.io/local-network-access/
Access-Control-Request-Local-Network
Access-Control-Allow-Local-Network

**Comment by robjtede** [comment]
updating crate feature in #320

**Comment by GillesPl** [comment]
> ~The specification has been renamed to local-network-access, and the headers have been renamed as well.~
> 
> ~https://wicg.github.io/local-network-access/ Access-Control-Request-Local-Network Access-Control-Allow-Local-Network~
> 
> It appears that the spec is still not finalized.

The spec is indeed not finalized yet, Google is going to enforce it (initially in May) September but it's a bit of a mess over there..
https://developer.chrome.com/blog/private-network-access-preflight/ (blog post with changes and updates)
https://developer.chrome.com/blog/private-network-access-update/ (official documentation from Google + Timeline)

**Pull request merged**
