### PR TITLE
Updated Cargo.toml to support Prost 0.10

### PR DESCRIPTION
**Pull request by TobiasDeBruijn**
## PR Type

Other

## PR Checklist

- [x] Tests for the changes have been added / updated.
- [x] Documentation comments have been added / updated.
- [x] A changelog entry has been made for the appropriate packages.
- [x] Format code with the nightly rustfmt (`cargo +nightly fmt`).

## Overview

This PR allows Prost 0.10 to work. This has no breaking changes as 0.9 is still supported as well.

### CODE REVIEW

**Comment by robjtede** [comment]
I'd rather bump the version and release a breaking change in this case.

**Comment by TobiasDeBruijn** [comment]
Sounds good!

**Comment by robjtede** [comment]
Needs a changelog entry.

**Comment by TobiasDeBruijn** [comment]
Should I also bump the major version?

**Comment by TobiasDeBruijn** [comment]
I'm unsure as to why the CI is failing, both build & clippy working on my local machine :thinking:

**Comment by robjtede** [comment]
think you need to update the dev-dependencies one as well

**Comment by TobiasDeBruijn** [comment]
Ah, good point. missed that one, will PR asap

**Review by robjtede — APPROVED** [review]

**Pull request merged**
