### PR TITLE
bump protobuf to 0.11

### PR DESCRIPTION
**Pull request by ahmed-masud**
## PR Type

Primary change is for the server to accept application/x-protobuf in addition to
application/protobuf as many clients do tend to send the other mime-type.

Bug Fix - Not really a bug-fix (but sorta)
Other - updated dependencies' versions

## PR Checklist

- [ ] Tests for the changes have been added / updated.
- [ ] Documentation comments have been added / updated.
- [X] A changelog entry has been made for the appropriate packages.
- [X] Format code with the nightly rustfmt (`cargo +nightly fmt`).

## Overview

* actix-protobuf now accepts application/x-protobuf
* Upgrading to prost 0.11 in actix-protobuf prepares for better 
refactoring down the line

### CODE REVIEW

**Comment by robjtede** [comment]
All patch versions are intentional.

Please do not bump version but instead place any change log items under Unreleased.

Thank you for your contribution.

**Comment by robjtede** [comment]
All patch versions are intentional.

Please do not bump version but instead place any change log items under Unreleased.

Thank you for your contribution.

**Comment by ahmed-masud** [comment]
> 

:-) I thought I was mucking that up a bit... I'll revert that

**Comment by ahmed-masud** [comment]
Reissuing the pull request with the bump to version removed and the change log fixed. :)

**Pull request closed without merging**
